<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>6</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <AssemblyName>Mz.Networking.SourceCopyValidation</AssemblyName>
        <RootNamespace>Mz.Networking.SourceCopyValidation</RootNamespace>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <SpaceEngineersBin64>E:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64</SpaceEngineersBin64>
    </PropertyGroup>

    <ItemGroup>
        <Compile
            Include="..\..\src\Mz.Networking.Core\*.cs"
            Link="Libraries\Mz.Networking.Core\%(Filename)%(Extension)" />
        <Compile
            Include="..\..\src\Mz.Networking.SpaceEngineers\*.cs"
            Link="Libraries\Mz.Networking.SpaceEngineers\%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference
            Include="Mal.Mdk2.ModAnalyzers"
            Version="2.1.16"
            PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="ProtoBuf.Net.Core">
            <HintPath>$(SpaceEngineersBin64)\ProtoBuf.Net.Core.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <Reference Include="Sandbox.Common">
            <HintPath>$(SpaceEngineersBin64)\Sandbox.Common.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <Reference Include="VRage.Game">
            <HintPath>$(SpaceEngineersBin64)\VRage.Game.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
</Project>
