<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <LangVersion>6</LangVersion>

    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <RootNamespace>Mz.SemanticVersioning</RootNamespace>
    <AssemblyName>Mz.SemanticVersioning</AssemblyName>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>